"""LLM client for test generation, test healing, response validation, and judge evaluation.

Owns:
- Invoking the underlying LLM provider with structured messages.
- Cleaning LLM responses (stripping markdown fences).
- Validating generated code with ``ast.parse`` before disk writes.
- Detecting hand-written test files to prevent accidental overwrite.
- The Judge evaluation and tripartite classification (:class:`JudgeOutcome`).

Does NOT:
- Execute tests or spawn subprocesses (that is ``runner.py``'s job).
- Watch filesystem events or manage worker loops.
- Implement provider-specific API protocols.

Guarantees:
- Never allows unparseable Python code to be treated as valid generated tests.
- Never overwrites hand-written test files without explicit ``force=True``.
- Classifies any ambiguous judge output as :attr:`JudgeOutcome.UNCLEAR`, which never heals.
"""

from __future__ import annotations

import ast
import asyncio
import re
from enum import StrEnum
from pathlib import Path
from typing import TYPE_CHECKING

from ghost.errors import HandwrittenTestOverwriteError, UnparseableCodeError
from ghost.indexer import budget_context, get_project_tree, walk_and_generate_json
from ghost.prompts import (
    HEADER_PREFIX,
    build_generation_prompt,
    build_healing_prompt,
    build_judge_prompt,
)

if TYPE_CHECKING:
    from ghost.config import GhostConfig
    from ghost.providers import BaseProvider

__all__ = [
    "JudgeOutcome",
    "LLMClient",
    "clean_llm_response",
    "ensure_can_overwrite_test",
    "is_ghost_managed_test",
    "parse_judge_response",
    "validate_test_code",
]

_MARKDOWN_BLOCK_RE = re.compile(r"^```(?:python)?\s*\n(.*?)\n```\s*$", re.DOTALL | re.IGNORECASE)


class JudgeOutcome(StrEnum):
    """The outcome of the Judge evaluating a test failure."""

    BUG_IN_CODE = "BUG_IN_CODE"
    FIX_TEST = "FIX_TEST"
    UNCLEAR = "UNCLEAR"


def parse_judge_response(raw_text: str) -> JudgeOutcome:
    """Parse raw LLM judge output into a typed :class:`JudgeOutcome`.

    Any ambiguous, conflicting, or non-matching response maps to ``UNCLEAR``.
    """
    cleaned = raw_text.strip().upper()
    has_bug = "BUG_IN_CODE" in cleaned
    has_fix = "FIX_TEST" in cleaned

    if has_bug and not has_fix:
        return JudgeOutcome.BUG_IN_CODE
    if has_fix and not has_bug:
        return JudgeOutcome.FIX_TEST
    return JudgeOutcome.UNCLEAR


def clean_llm_response(raw_text: str) -> str:
    """Strip markdown code block fences and surrounding whitespace from LLM output."""
    text = raw_text.strip()
    match = _MARKDOWN_BLOCK_RE.search(text)
    if match:
        return match.group(1).strip()
    if text.startswith("```python"):
        text = text[len("```python") :]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()


def validate_test_code(code: str, source_path: Path | str = "") -> ast.AST:
    """Validate that *code* is syntactically valid Python.

    Raises :class:`~ghost.errors.UnparseableCodeError` on syntax error.
    """
    try:
        return ast.parse(code, filename=str(source_path))
    except SyntaxError as err:
        raise UnparseableCodeError(source_path, str(err)) from err


def is_ghost_managed_test(test_file: Path, content: str | None = None) -> bool:
    """Determine whether an existing test file was generated by Ghost.

    Ghost-generated files begin with the signature ``# Generated at:`` header
    within the first few lines.
    """
    if content is None:
        if not test_file.is_file():
            return False
        try:
            content = test_file.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            return False

    first_lines = content.splitlines()[:5]
    return any(HEADER_PREFIX in line for line in first_lines)


def ensure_can_overwrite_test(test_file: Path, *, force: bool = False) -> None:
    """Verify it is safe to write to *test_file*.

    Raises :class:`~ghost.errors.HandwrittenTestOverwriteError` if *test_file*
    exists and is not Ghost-managed, unless *force* is ``True``.
    """
    if force:
        return

    if test_file.is_file() and not is_ghost_managed_test(test_file):
        raise HandwrittenTestOverwriteError(test_file)


def _prepare_generation_context(
    source_path: Path,
    project_root: Path,
    config: GhostConfig,
) -> tuple[str, str, str, dict[str, str]]:
    resolved_src = source_path.resolve()
    resolved_root = project_root.resolve()
    rel_path = resolved_src.relative_to(resolved_root).as_posix()
    source_code = resolved_src.read_text(encoding="utf-8")

    tree_str = get_project_tree(resolved_root, config.scanner)
    index = walk_and_generate_json(resolved_root, scanner_config=config.scanner)
    budgeted = budget_context(index, target_file=rel_path, root=resolved_root)

    return source_code, rel_path, tree_str, budgeted


def _prepare_healing_context(
    source_path: Path,
    test_file: Path,
    project_root: Path,
    config: GhostConfig,
) -> tuple[str, str, str, str, dict[str, str]]:
    resolved_src = source_path.resolve()
    resolved_test = test_file.resolve()
    resolved_root = project_root.resolve()
    rel_path = resolved_src.relative_to(resolved_root).as_posix()

    source_code = resolved_src.read_text(encoding="utf-8")
    test_code = resolved_test.read_text(encoding="utf-8")

    tree_str = get_project_tree(resolved_root, config.scanner)
    index = walk_and_generate_json(resolved_root, scanner_config=config.scanner)
    budgeted = budget_context(index, target_file=rel_path, root=resolved_root)

    return source_code, test_code, rel_path, tree_str, budgeted


def _read_file_sync(path: Path) -> str:
    return path.read_text(encoding="utf-8")


class LLMClient:
    """High-level client orchestrating prompt generation, provider calls, and validation."""

    def __init__(self, provider: BaseProvider, config: GhostConfig) -> None:
        self.provider = provider
        self.config = config

    async def generate_test(
        self,
        source_path: Path,
        project_root: Path,
        *,
        timestamp: str | None = None,
    ) -> str:
        """Generate, clean, and syntactically validate tests for *source_path*."""
        source_code, rel_path, tree_str, budgeted = await asyncio.to_thread(
            _prepare_generation_context, source_path, project_root, self.config
        )

        prompt = build_generation_prompt(
            source_code=source_code,
            source_path=rel_path,
            project_tree=tree_str,
            context=budgeted,
            framework=self.config.tests.framework,
            timestamp=timestamp,
        )

        messages = [{"role": "user", "content": prompt}]
        raw = await self.provider.chat(
            messages=messages,
            model=self.config.ai.model,
            temperature=self.config.ai.temperature,
        )

        cleaned = clean_llm_response(raw)
        validate_test_code(cleaned, source_path=rel_path)
        return cleaned

    async def heal_test(
        self,
        source_path: Path,
        test_file: Path,
        error_output: str,
        project_root: Path,
        *,
        return_code: int = 1,
        timestamp: str | None = None,
    ) -> str:
        """Generate, clean, and validate healed test code after a test run failure."""
        source_code, test_code, rel_path, tree_str, budgeted = await asyncio.to_thread(
            _prepare_healing_context, source_path, test_file, project_root, self.config
        )

        prompt = build_healing_prompt(
            source_code=source_code,
            source_path=rel_path,
            test_code=test_code,
            error_output=error_output,
            project_tree=tree_str,
            context=budgeted,
            framework=self.config.tests.framework,
            return_code=return_code,
            timestamp=timestamp,
        )

        messages = [{"role": "user", "content": prompt}]
        raw = await self.provider.chat(
            messages=messages,
            model=self.config.ai.model,
            temperature=self.config.ai.temperature,
        )

        cleaned = clean_llm_response(raw)
        validate_test_code(cleaned, source_path=rel_path)
        return cleaned

    async def consult_the_judge(
        self,
        source_path: Path,
        test_file: Path,
        error_output: str,
    ) -> JudgeOutcome:
        """Ask the model to evaluate whether a test failure is BUG_IN_CODE or FIX_TEST."""
        source_code = await asyncio.to_thread(_read_file_sync, source_path)
        test_code = await asyncio.to_thread(_read_file_sync, test_file)

        prompt = build_judge_prompt(
            source_code=source_code,
            test_code=test_code,
            error_output=error_output,
        )

        messages = [{"role": "user", "content": prompt}]
        raw = await self.provider.chat(
            messages=messages,
            model=self.config.ai.model,
            temperature=self.config.ai.temperature,
        )

        return parse_judge_response(raw)
